# Generated by Django 5.1.5 on 2025-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0002_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
